const advantagesDataArray = [
  {
    id: 1,
    img: "./img/company-advantages/delivery.svg",
    mainText: "Доставка по России",
    subText: "Осуществляется транспортными компаниями или Почтой России",
  },
  {
    id: 2,
    img: "./img/company-advantages/pay.svg",
    mainText: "On-line оплата на сайте",
    subText: "Оплата производится банковской картой и электронными деньгами",
  },
  {
    id: 3,
    img: "./img/company-advantages/sale.svg",
    mainText: "Система скидок",
    subText: "Накопительные скидки и бонусная программа для наших клиентов",
  },
];

const productsDataArray = [
  {
    id: 1,
    img: "./img/products/refurb-2013-imac-215-gallery.png",
    productTitle: "Компьютеры",
    productCount: "393 товара",
    productCountNumber: 393,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 2,
    img: "./img/products/ekiden-mens-running-shorts-black.png",
    productTitle: "Одежда",
    productCount: "245 товара",
    productCountNumber: 245,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 3,
    img: "./img/products/refurb-2013-imac-215-gallery.png",
    productTitle: "Электроника",
    productCount: "456 товара",
    productCountNumber: 456,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 4,
    img: "./img/products/shop_property_file_213_273.png",
    productTitle: "Автотовары",
    productCount: "128 товара",
    productCountNumber: 128,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 5,
    img: "./img/products/2.png",
    productTitle: "Спорт и отдых",
    productCount: "197 товара",
    productCountNumber: 197,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 6,
    img: "./img/products/joie-transcend-1.png",
    productTitle: "Детские товары",
    productCount: "86 товара",
    productCountNumber: 86,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 7,
    img: "./img/products/IzIxNTExOjA6MDow0.png",
    productTitle: "Туризм и рыбалка",
    productCount: "92 товара",
    productCountNumber: 92,
    productArrowImg: "./img/icons/arrow.svg",
  },
  {
    id: 8,
    img: "./img/products/1.png",
    productTitle: "Инструмент",
    productCount: "104 товара",
    productCountNumber: 104,
    productArrowImg: "./img/icons/arrow.svg",
  },
];

const bestsellersDataArray = [
  {
    id: 1,
    bestsellerSearchIcon: "./img/icons/magnify_icon.svg",
    bestsellerHitIconText: "hit",
    bestsellerYoutubeIcon: "./img/icons/youtube.svg",
    bestsellerImg: "./img/bestsellers/Iphone_8_image.png",
    bestsellerExpansionIcon: "./img/icons/expand_icon(2).svg",
    bestsellerTitle: "Смартфон Apple Iphone 8 64GB Gold",
    bestsellerStarsRatingImg: "./img/rating-stars/stars.svg",
    bestsellerReviews: 10,
    bestsellerActualPrice: "56 890",
    bestsellerOldPrice: "56 990",
    bestsellerProductAvailableIcon: "./img/icons/available.svg",
    bestsellerIsAvailableText: "В наличии",
    bestsellerAddToCartBtn: "В корзину",
    bestsellerComparisonIcon: "./img/icons/comparison_icon.svg",
    bestsellerFavoriteIcon: "./img/icons/favorite_icon.svg",
    bestsellerOneClickBuy: "Купить в 1 клик",
  },
  {
    id: 2,
    bestsellerSearchIcon: "./img/icons/magnify_icon.svg",
    bestsellerHitIconText: "hit",
    bestsellerYoutubeIcon: "./img/icons/youtube.svg",
    bestsellerImg: "./img/bestsellers/samsung-galaxy-s8-event-live.png",
    bestsellerExpansionIcon: "./img/icons/expand_icon(2).svg",
    bestsellerTitle: "Смартфон Samsung Galaxy S8 64GB Black",
    bestsellerStarsRatingImg: "./img/rating-stars/stars(1).svg",
    bestsellerReviews: 12,
    bestsellerActualPrice: "49 990",
    bestsellerOldPrice: "54 990",
    bestsellerProductAvailableIcon: "./img/icons/available.svg",
    bestsellerIsAvailableText: "В наличии",
    bestsellerAddToCartBtn: "В корзину",
    bestsellerComparisonIcon: "./img/icons/comparison_icon.svg",
    bestsellerFavoriteIcon: "./img/icons/favorite_icon.svg",
    bestsellerOneClickBuy: "Купить в 1 клик",
  },
  {
    id: 3,
    bestsellerSearchIcon: "./img/icons/magnify_icon.svg",
    bestsellerHitIconText: "hit",
    bestsellerYoutubeIcon: "./img/icons/youtube.svg",
    bestsellerImg: "./img/bestsellers/tl1001508402@2x.png",
    bestsellerExpansionIcon: "./img/icons/expand_icon(2).svg",
    bestsellerTitle: "Смартфон Huawei Honor 9 64GB Blue",
    bestsellerStarsRatingImg: "./img/rating-stars/stars(2).svg",
    bestsellerReviews: 8,
    bestsellerActualPrice: "26 990",
    bestsellerOldPrice: "",
    bestsellerProductAvailableIcon: "./img/icons/available.svg",
    bestsellerIsAvailableText: "В наличии",
    bestsellerAddToCartBtn: "В корзину",
    bestsellerComparisonIcon: "./img/icons/comparison_icon.svg",
    bestsellerFavoriteIcon: "./img/icons/favorite_icon.svg",
    bestsellerOneClickBuy: "Купить в 1 клик",
  },
  {
    id: 4,
    bestsellerSearchIcon: "./img/icons/magnify_icon.svg",
    bestsellerHitIconText: "hit",
    bestsellerYoutubeIcon: "./img/icons/youtube.svg",
    bestsellerImg:
      "./img/bestsellers/Asus-Zenfone-4-Max-ZC554KL-Octa-Core-1.png",
    bestsellerExpansionIcon: "./img/icons/expand_icon(2).svg",
    bestsellerTitle: "Смартфон ASUS ZenFone 4 Max ZC554KL 16GB Black",
    bestsellerStarsRatingImg: "./img/rating-stars/stars(3).svg",
    bestsellerReviews: 5,
    bestsellerActualPrice: "13 990",
    bestsellerOldPrice: "",
    bestsellerProductAvailableIcon: "./img/icons/available.svg",
    bestsellerIsAvailableText: "В наличии",
    bestsellerAddToCartBtn: "В корзину",
    bestsellerComparisonIcon: "./img/icons/comparison_icon.svg",
    bestsellerFavoriteIcon: "./img/icons/favorite_icon.svg",
    bestsellerOneClickBuy: "Купить в 1 клик",
  },
];

export { advantagesDataArray, productsDataArray, bestsellersDataArray };
